// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqhhcejcbwdbjywhmpkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxaGhjZWpjYndkYmp5d2htcGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Nzc1MzMsImV4cCI6MjA2OTE1MzUzM30.5uaCu4Vw6DxyjlnINy5UQwEOWwbS2BCVNSaygE8zGYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});